use super::*;
pub(crate) use rawjs_common::SourceLocation;

mod loc_to_compile_top_level_await_marks_program_async;
pub(crate) use self::loc_to_compile_top_level_await_marks_program_async::*;
mod compile_await_in_sync_function_still_errors_to_binary_add;
pub(crate) use self::compile_await_in_sync_function_still_errors_to_binary_add::*;
mod compile_all_binary_ops_to_variable_no_init;
pub(crate) use self::compile_all_binary_ops_to_variable_no_init::*;
mod compile_variable_read_to_do_while_loop;
pub(crate) use self::compile_variable_read_to_do_while_loop::*;
mod compile_for_loop_to_function_declaration;
pub(crate) use self::compile_for_loop_to_function_declaration::*;
mod compile_function_body_correct_to_computed_member;
pub(crate) use self::compile_function_body_correct_to_computed_member::*;
mod compile_optional_call_to_conditional_expression;
pub(crate) use self::compile_optional_call_to_conditional_expression::*;
mod compile_logical_and_to_compound_assignment;
pub(crate) use self::compile_logical_and_to_compound_assignment::*;
mod compile_logical_or_assignment_to_sequence;
pub(crate) use self::compile_logical_or_assignment_to_sequence::*;
mod compile_block_scoping_to_disassemble_output;
pub(crate) use self::compile_block_scoping_to_disassemble_output::*;
mod compile_nested_functions_to_delete_member;
pub(crate) use self::compile_nested_functions_to_delete_member::*;
mod compile_delete_non_member_to_labeled_while;
pub(crate) use self::compile_delete_non_member_to_labeled_while::*;
mod compile_repl_to_last_expression_result;
pub(crate) use self::compile_repl_to_last_expression_result::*;
